using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEditor;
using UnityEngine;
using UnityEngine.SceneManagement;

public class PauseMenu : MonoBehaviour
{
    public static bool GameIsPaused = false;
    public GameObject PauseMenuUI;


    // Checks if the game is getting paused by pressing "Escape"
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            if (GameIsPaused)
            {
                Resume();
            }
            else
            {

                Pause();
            }

        }
        if (GameIsPaused = true && Input.GetKeyDown(KeyCode.Escape))
        {
            transform.GetChild(1).gameObject.SetActive(false);
        }
    }
    //makes the game resume
    public void Resume()
    {
        PauseMenuUI.SetActive(false);
        Time.timeScale = 1f;
        GameIsPaused = false;
    }
    //makes the game pause
    void Pause()
    {
        PauseMenuUI.SetActive(true);
        Time.timeScale = 0f;
        GameIsPaused = true;
    }
    //loads u back to main menu
    public void quitgame()
    {
        SceneManager.LoadScene(0);
    }


}
//gjord av Lucas